### ISSUE TITLE
pretrain_semantic_depth.sh

### ISSUE THREAD

**Issue by xuwanpeng12** [alopezgit/DESC#1]
When I run the following script ./pretrain_semantic_depth.sh VKITTI_ROOT_FOLDER KITTI_ROOT_FOLDER, the following error appears. 

Traceback (most recent call last):
  File "train.py", line 55, in <module>
    model.optimize_parameters()
  File "/userhome/DESC/models/DESC_model.py", line 513, in optimize_parameters
    self.backward_G()
  File "/userhome/DESC/models/DESC_model.py", line 368, in backward_G
    self.net_s2t.train()
AttributeError: 'DESCModel' object has no attribute 'net_s2t'

Is my path set incorrectly? In addition, do pretrain_depth.sh and pretrain_semantic_depth.sh share a checkpoints folder, or are they stored separately?@alopezgit

**Comment by xuwanpeng12** [comment]
Looking forward to your reply, thank you very much！

**Comment by alopezgit** [comment]
Hi,

There was a bug in the code when using pretrain_semantic_depth, thank you for opening the issue. I made some changes, let me know if it works now. :smile: 

Also, both pretrain_depth.sh and pretrain_semantic_depth.sh should save the models in the same folder. Then `joint_training.sh` should load the models from that folder.

**Comment by xuwanpeng12** [comment]
Thank you for your kind help, it can work now.
