### ISSUE TITLE
The image of ground truth depth

### ISSUE THREAD

**Issue by xuheyang** [alopezgit/DESC#2]
I'm so sorry to disturb you！

“Ground truth depth is linearly interpolated for visualization” , I don't know how to get such depth images.
Can you release your code for getting ground truth depth?

Looking forward to your reply, thank you very much！

**Comment by alopezgit** [comment]
Hi,
We used this code to interpolate the KITTI ground-truth depth for visualization:
```
from scipy.interpolate import LinearNDInterpolator
import numpy as np
def lin_interp(depth):
    depth = np.squeeze(depth)
    shape = depth.shape[-2:]
    xy = (depth!=0).nonzero()
    d = depth[xy]
    xy = [xy[1], xy[0]]
    xy = np.stack(xy, 1)
    xyd = np.concatenate([xy, np.expand_dims(d, 1)], 1)
    m, n = depth.shape
    ij, d = xyd[:, 1::-1], xyd[:, 2]
    f = LinearNDInterpolator(ij, d, fill_value=0)
    J, I = np.meshgrid(np.arange(n), np.arange(m))
    IJ = np.vstack([I.flatten(), J.flatten()]).T
    depth = f(IJ).reshape(shape)
    depth = depth.clip(0, 80)
    return depth
```
It needs a sparse depth map (i.e., a KITTI ground-truth map) in a numpy format and with a shape (H,W).
To generate a similar figure as in the paper (so same colormap), you can then use:
```
import matplotlib as mpl
import matplotlib.cm as cm
def convert_array_vis(depth):
    mask = depth!=0
    depth = depth.clip(1, 80)
    # We actually visualize disparity as
    # the qualitative differences are easier to see
    disparity = 1/depth
    vmax = np.percentile(disparity[mask], 95)
    normalizer = mpl.colors.Normalize(vmin=disparity.min(), vmax=vmax)
    mapper = cm.ScalarMappable(norm=normalizer, cmap='magma')
    mask = np.repeat(np.expand_dims(mask,-1), 3, -1)
    colormapped_im = (mapper.to_rgba(disparity)[:, :, :3] * 255).astype(np.uint8)
    colormapped_im[~mask] = 255
    return colormapped_im
```

Again, this is only done for visualization purposes. For evaluation, we use the sparse ground-truth depth from [Monodepth2](https://github.com/nianticlabs/monodepth2) as explained in the README file.

**Comment by xuheyang** [comment]
Although my question is a bit low-level, you are still eager to help.
thank you very much!

best!
