### ISSUE TITLE
The color of visualization for depth map

### ISSUE THREAD

**Issue by ccc870206** [alopezgit/DESC#3]
Hi, 
In your paper, I guess that your visualization for depth map uses cmap 'magma'.
I use the same cmap but get the following result.
![0_pred](https://user-images.githubusercontent.com/32905951/139858166-b5f226b5-51c4-410e-9f00-7631b0e0847c.png)

It looks more bright and yellow. I'm not sure if I make mistake.
Therefore, could you tell how you visualize the depth map or provide the code?
Many thanks.

**Comment by alopezgit** [comment]
Hi,

The function I used should be a modification of the following one. Try to play with the np.percentile parameters to see if you can make it look like you want to, as it limits the output colormap to a range of depth (or disparity in this code) values.
```
import PIL.Image as pil
import numpy as np
import matplotlib as mpl
import matplotlib.cm as cm
def convert_array_to_pil(depth_map):
    # Input: depth_map -> HxW numpy array with depth values 
    # Output: colormapped_im -> HxW numpy array with colorcoded depth values
    mask = depth_map!=0
    disp_map = 1/depth_map
    vmax = np.percentile(disp_map[mask], 95)
    vmin = np.percentile(disp_map[mask], 5)
    normalizer = mpl.colors.Normalize(vmin=vmin, vmax=vmax)
    mapper = cm.ScalarMappable(norm=normalizer, cmap='magma')
    mask = np.repeat(np.expand_dims(mask,-1), 3, -1)
    colormapped_im = (mapper.to_rgba(disp_map)[:, :, :3] * 255).astype(np.uint8)
    colormapped_im[~mask] = 255
    return colormapped_im
```

**Comment by alopezgit** [comment]
I'm closing the issue for now, feel free to open another one if it is still not solved.

**Comment by ccc870206** [comment]
It's really helpful! Thank you!

**Comment by sunanditaghosh29** [comment]
For a segmented image, can we go for a colormap as per with the known depth of the segments?
